// <auto-generated />
using System;
using DATN.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATN.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250910143407_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DATN.Domain.Entities.danh_muc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ma_dinh_danh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("mo_ta")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ngay_chinh_sua")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ngay_tao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nguoi_chinh_sua")
                        .HasColumnType("longtext");

                    b.Property<string>("nguoi_tao")
                        .HasColumnType("longtext");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("trang_thai")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("danh_muc");
                });

            modelBuilder.Entity("DATN.Domain.Entities.dieu_huong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("cap_dieu_huong")
                        .HasColumnType("int");

                    b.Property<Guid?>("dieu_huong_cap_tren_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("duong_dan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("mo_ta")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ngay_chinh_sua")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ngay_tao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nguoi_chinh_sua")
                        .HasColumnType("longtext");

                    b.Property<string>("nguoi_tao")
                        .HasColumnType("longtext");

                    b.Property<int>("so_thu_tu")
                        .HasColumnType("int");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("dieu_huong");
                });

            modelBuilder.Entity("DATN.Domain.Entities.dieu_huong_2_command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("command")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid?>("command_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("dieu_huong_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("command_id");

                    b.HasIndex("dieu_huong_id");

                    b.ToTable("dieu_huong_2_command");
                });

            modelBuilder.Entity("DATN.Domain.Entities.dm_command", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("command")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.ToTable("dm_command");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nguoi_dung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<bool?>("gioi_tinh")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("is_doi_mk")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("mat_khau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ngay_chinh_sua")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ngay_doi_mk")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ngay_sinh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ngay_tao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nguoi_chinh_sua")
                        .HasColumnType("longtext");

                    b.Property<string>("nguoi_tao")
                        .HasColumnType("longtext");

                    b.Property<string>("salt_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("so_dien_thoai")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("tai_khoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("trang_thai")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("nguoi_dung");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nguoi_dung_2_danh_muc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("danh_muc_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("nguoi_dung_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("danh_muc_id");

                    b.HasIndex("nguoi_dung_id");

                    b.ToTable("nguoi_dung_2_danh_muc");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nguoi_dung_2_nhom_nguoi_dung", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("mac_dinh")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("nguoi_dung_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("nhom_nguoi_dung_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("nguoi_dung_id");

                    b.HasIndex("nhom_nguoi_dung_id");

                    b.ToTable("nguoi_dung_2_nhom_nguoi_dung");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nhat_ky_he_thong", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("command")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid?>("command_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("detail")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("dieu_huong_id")
                        .HasColumnType("char(36)");

                    b.Property<int?>("level")
                        .HasColumnType("int");

                    b.Property<int?>("loai")
                        .HasColumnType("int");

                    b.Property<string>("tai_khoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ten")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("command_id");

                    b.HasIndex("dieu_huong_id");

                    b.ToTable("nhat_ky_he_thong");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nhom_nguoi_dung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ngay_chinh_sua")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ngay_tao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nguoi_chinh_sua")
                        .HasColumnType("longtext");

                    b.Property<string>("nguoi_tao")
                        .HasColumnType("longtext");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("nhom_nguoi_dung");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nhom_nguoi_dung_2_command", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("command")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid?>("command_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("dieu_huong_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("nhom_nguoi_dung_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("dieu_huong_id");

                    b.HasIndex("nhom_nguoi_dung_id");

                    b.ToTable("nhom_nguoi_dung_2_command");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nhom_nguoi_dung_2_dieu_huong", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("dieu_huong_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("nhom_nguoi_dung_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("dieu_huong_id");

                    b.HasIndex("nhom_nguoi_dung_id");

                    b.ToTable("nhom_nguoi_dung_2_dieu_huong");
                });

            modelBuilder.Entity("DATN.Domain.Entities.tai_lieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("cap_do")
                        .HasColumnType("int");

                    b.Property<string>("duong_dan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_share")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ngay_chinh_sua")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ngay_tao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nguoi_chinh_sua")
                        .HasColumnType("longtext");

                    b.Property<string>("nguoi_tao")
                        .HasColumnType("longtext");

                    b.Property<int>("phien_ban")
                        .HasColumnType("int");

                    b.Property<string>("phong_ban")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tai_lieu");
                });

            modelBuilder.Entity("DATN.Domain.Entities.tai_lieu_2_nguoi_dung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("nguoi_dung_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("tai_lieu_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("nguoi_dung_id");

                    b.HasIndex("tai_lieu_id");

                    b.ToTable("tai_lieu_2_nguoi_dung");
                });

            modelBuilder.Entity("DATN.Domain.Entities.dieu_huong_2_command", b =>
                {
                    b.HasOne("DATN.Domain.Entities.dm_command", "dm_command")
                        .WithMany("ds_dieu_huong_2_command")
                        .HasForeignKey("command_id");

                    b.HasOne("DATN.Domain.Entities.dieu_huong", "dieu_Huong")
                        .WithMany("ds_dieu_huong_2_command")
                        .HasForeignKey("dieu_huong_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dieu_Huong");

                    b.Navigation("dm_command");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nguoi_dung_2_danh_muc", b =>
                {
                    b.HasOne("DATN.Domain.Entities.danh_muc", "danh_muc")
                        .WithMany("ds_nguoi_dung")
                        .HasForeignKey("danh_muc_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN.Domain.Entities.nguoi_dung", "nguoi_dung")
                        .WithMany("ds_phong_ban")
                        .HasForeignKey("nguoi_dung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("danh_muc");

                    b.Navigation("nguoi_dung");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nguoi_dung_2_nhom_nguoi_dung", b =>
                {
                    b.HasOne("DATN.Domain.Entities.nguoi_dung", "nguoi_dung")
                        .WithMany("ds_nhom_nguoi_dung")
                        .HasForeignKey("nguoi_dung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN.Domain.Entities.nhom_nguoi_dung", "nhom_nguoi_dung")
                        .WithMany("ds_nguoi_dung")
                        .HasForeignKey("nhom_nguoi_dung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nguoi_dung");

                    b.Navigation("nhom_nguoi_dung");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nhat_ky_he_thong", b =>
                {
                    b.HasOne("DATN.Domain.Entities.dm_command", "dm_command")
                        .WithMany("ds_system_log")
                        .HasForeignKey("command_id");

                    b.HasOne("DATN.Domain.Entities.dieu_huong", "dieu_huong")
                        .WithMany("ds_nhat_ky_he_thong")
                        .HasForeignKey("dieu_huong_id");

                    b.Navigation("dieu_huong");

                    b.Navigation("dm_command");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nhom_nguoi_dung_2_command", b =>
                {
                    b.HasOne("DATN.Domain.Entities.dieu_huong", "dieu_huong")
                        .WithMany("ds_nhom_nguoi_dung_2_command")
                        .HasForeignKey("dieu_huong_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN.Domain.Entities.nhom_nguoi_dung", "nhom_nguoi_dung")
                        .WithMany("ds_dm_command")
                        .HasForeignKey("nhom_nguoi_dung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dieu_huong");

                    b.Navigation("nhom_nguoi_dung");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nhom_nguoi_dung_2_dieu_huong", b =>
                {
                    b.HasOne("DATN.Domain.Entities.dieu_huong", "dieu_huong")
                        .WithMany("ds_nhom_nguoi_dung")
                        .HasForeignKey("dieu_huong_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN.Domain.Entities.nhom_nguoi_dung", "nhom_nguoi_dung")
                        .WithMany("ds_dieu_huong")
                        .HasForeignKey("nhom_nguoi_dung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dieu_huong");

                    b.Navigation("nhom_nguoi_dung");
                });

            modelBuilder.Entity("DATN.Domain.Entities.tai_lieu_2_nguoi_dung", b =>
                {
                    b.HasOne("DATN.Domain.Entities.nguoi_dung", "nguoi_dung")
                        .WithMany("ds_tai_lieu")
                        .HasForeignKey("nguoi_dung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN.Domain.Entities.tai_lieu", "tai_lieu")
                        .WithMany("ds_nguoi_dung")
                        .HasForeignKey("tai_lieu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nguoi_dung");

                    b.Navigation("tai_lieu");
                });

            modelBuilder.Entity("DATN.Domain.Entities.danh_muc", b =>
                {
                    b.Navigation("ds_nguoi_dung");
                });

            modelBuilder.Entity("DATN.Domain.Entities.dieu_huong", b =>
                {
                    b.Navigation("ds_dieu_huong_2_command");

                    b.Navigation("ds_nhat_ky_he_thong");

                    b.Navigation("ds_nhom_nguoi_dung");

                    b.Navigation("ds_nhom_nguoi_dung_2_command");
                });

            modelBuilder.Entity("DATN.Domain.Entities.dm_command", b =>
                {
                    b.Navigation("ds_dieu_huong_2_command");

                    b.Navigation("ds_system_log");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nguoi_dung", b =>
                {
                    b.Navigation("ds_nhom_nguoi_dung");

                    b.Navigation("ds_phong_ban");

                    b.Navigation("ds_tai_lieu");
                });

            modelBuilder.Entity("DATN.Domain.Entities.nhom_nguoi_dung", b =>
                {
                    b.Navigation("ds_dieu_huong");

                    b.Navigation("ds_dm_command");

                    b.Navigation("ds_nguoi_dung");
                });

            modelBuilder.Entity("DATN.Domain.Entities.tai_lieu", b =>
                {
                    b.Navigation("ds_nguoi_dung");
                });
#pragma warning restore 612, 618
        }
    }
}
